import joi from "joi";

export const new_nftmarket_trade = joi.object({
    blockchain: joi.string().required(),
    project: joi.string().required(),
    version: joi.string().required(),
    block_date: joi.string().required(),
    block_month: joi.string().required(),
    block_time : joi.string().required(),
    token_id : joi.string().required(),
    collection: joi.string().required(),
    amount_usd: joi.number().required(),
    token_standard: joi.string().required(),
    trade_type: joi.string().required(),
    number_of_items: joi.number().required(),
    trade_category: joi.string().required(),
    evt_type: joi.string().required(),
    seller: joi.string().required(),
    buyer: joi.string().required(),
    amount_original: joi.string().required(),
    amount_raw: joi.string().required(),
    currency_symbol: joi.string().required(),
    nft_contract_address: joi.string().required(),
    project_contract_address: joi.string().required(),
    aggregator_name: joi.string().required(),
    aggregator_address: joi.string().required(),
    block_number: joi.string().required(),
    tx_hash: joi.string().required(),
    tx_from: joi.string().required(),
    tx_to: joi.string().required(),
    platform_fee_amount_raw: joi.string().required(),
    platform_fee_amount: joi.string().required(),
    platform_fee_amount_usd: joi.number().required(),
    platform_fee_percentage: joi.number().required(),
    royalty_fee_receive_address: joi.string().required(),
    royalty_fee_currency_symbol: joi.string().required(),
    royalty_fee_amount_raw: joi.string().required(),
    royalty_fee_amount: joi.string().required(),
    royalty_fee_amount_usd: joi.number().required()
})